# Letzte Versionsaktualisierung: 20.Mai.2025

name: loeschwasserfoerderung
description: "Applikation zur automatischen Berechnung von Relaisleitungen"
publish_to: 'none'
version: 1.31.58

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  #Map
  flutter_map: ^8.1.1
  flutter_map_cancellable_tile_provider: ^3.1.0
  #Location
  flutter_map_location_marker: ^10.1.0
  latlong2: ^0.9.1
  geolocator: ^14.0.0
  #Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  #API Communication
  http: ^1.4.0
  dio: ^5.8.0+1
  #Urls
  url_launcher: ^6.3.1
  #Audio
  audioplayers: ^6.4.0
  #Email
  email_validator: ^3.0.0
  #.env
  flutter_dotenv: ^5.2.1
  #AutoComplete
  flutter_typeahead: ^5.2.0
  #Icon
  flutter_launcher_icons: ^0.14.3
  #Background Service
  flutter_background_service: ^5.1.0
  #Notification
  awesome_notifications: ^0.10.1
  #Permissions
  permission_handler: ^12.0.0+1
  #Encrypt/Decrypt
  crypto: ^3.0.6
  encrypt: ^5.0.3
  #Trailer
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true

flutter:
  assets:
    - assets/icons/icon.png
    - assets/icons/icon.ico
    - assets/sounds/notification.mp3
    - assets/config/.env
    - assets/config/.env_web
    - assets/hydrant_logos/loeschwasserbehaelter.png
    - assets/hydrant_logos/loeschwasserbrunnen.png
    - assets/hydrant_logos/loeschwasserteichUndNaturteichUndSchwimmbad.png
    - assets/hydrant_logos/saugstelle.png
    - assets/hydrant_logos/ueberflurhydrant.png
    - assets/hydrant_logos/unterflurhydrantUndSchachthydrant.png
  uses-material-design: true